### ISSUE TITLE
UnboundLocalError: local variable 'sizze_391' referenced before assignment

### ISSUE THREAD

**Issue by wvdschel** [HIPERFIT/futhark#333]
I have the following Futhark code, which compiles fine with `futhark-pyopencl --library test.fut`:
```
type rec = { first : f32, second : f32 }

let arr2rec(arr: [2]f32): rec =
        { first = arr[0],
          second = arr[1] }

let rec2arr(rc: rec): [2]f32 =
        [ #first rc,
          #second rc ]

let main(data: [][2]f32): [][2]f32 =
        let recs = map arr2rec data
        in map rec2arr recs
```

But this gives me the follow error in Python:
```
Python 3.6.1 (default, Mar 23 2017, 13:04:44) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
>>> t = test.test()
Warning: Device limits tile size to 22 (setting was 32)
>>> t.main([[1,2]])
Traceback (most recent call last):
  File "/home/wim/Unison/Code/Futhark/gravity/test.py", line 1980, in main
    assert (sizze_391 == np.int32(data_mem_429_ext.shape[np.int32(0)])), 'variant dimension wrong'
UnboundLocalError: local variable 'sizze_391' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wim/Unison/Code/Futhark/gravity/test.py", line 1982, in main
    sizze_391 = np.int32(data_mem_429_ext.shape[np.int32(0)])
AttributeError: 'list' object has no attribute 'shape'
>>> t.main([[1,2]])
```

I've tried removing the `#n` from the definition of main, but I get the same error.

What am I doing wrong here?

**Comment by wvdschel** [comment]
Never mind, from the benchmark repo I figured out I need to wrap the data into a `numpy.array`.

**Comment by Athas** [comment]
The reason is that you are passing a Python list, but those entry points
expect Numpy ndarrays.

In general, the generated Python code is not very diligent about
checking the types of passed-in values.  I'll make a check for this one,
at least.

-- 
\  Troels
/\ Henriksen
