### ISSUE TITLE
Futhark seems to leak resources

### ISSUE THREAD

**Issue by wvdschel** [HIPERFIT/futhark#336]
When running any Futhark code on my Ubuntu box using the beignet drivers from the official repositories, I get the following errors after a while:

```
Starting main loop
/build/beignet-5qGeBM/beignet-1.1.1/src/intel/intel_gpgpu.c:959: Cannot allocate memory.
/build/beignet-5qGeBM/beignet-1.1.1/src/intel/intel_gpgpu.c:959: Cannot allocate memory.
/build/beignet-5qGeBM/beignet-1.1.1/src/intel/intel_gpgpu.c:959: Cannot allocate memory.
/build/beignet-5qGeBM/beignet-1.1.1/src/intel/intel_gpgpu.c:959: Cannot allocate memory.
/build/beignet-5qGeBM/beignet-1.1.1/src/intel/intel_gpgpu.c:959: Cannot allocate memory.
Traceback (most recent call last):
  File "./main.py", line 163, in <module>
    if __name__ == '__main__': main()
  File "./main.py", line 117, in main
    galaxy_demo.update()
  File "./main.py", line 75, in update
    self.bodies = update_galaxy(self.step, self.bodies)
  File "/media/data/Stack/Unison/Code/Futhark/gravity/generated/galaxy_opencl.py", line 2535, in main
    sizze_2676, steps_2677)
  File "/media/data/Stack/Unison/Code/Futhark/gravity/generated/galaxy_opencl.py", line 2493, in futhark_main
    (np.long(group_sizze_2838),))
  File "/home/kodi/.local/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 2168, in enqueue_nd_range_kernel
    global_work_size, local_work_size, c_wait_for, num_wait_for))
  File "/home/kodi/.local/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 632, in _handle_error
    raise e
pyopencl.cffi_cl.RuntimeError: clEnqueueNDRangeKernel failed: OUT_OF_RESOURCES
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 757, in get_code
  File "<frozen importlib._bootstrap_external>", line 471, in _validate_bytecode_header
MemoryError

Original exception was:
Traceback (most recent call last):
  File "./main.py", line 163, in <module>
    if __name__ == '__main__': main()
  File "./main.py", line 117, in main
    galaxy_demo.update()
  File "./main.py", line 75, in update
    self.bodies = update_galaxy(self.step, self.bodies)
  File "/media/data/Stack/Unison/Code/Futhark/gravity/generated/galaxy_opencl.py", line 2535, in main
    sizze_2676, steps_2677)
  File "/media/data/Stack/Unison/Code/Futhark/gravity/generated/galaxy_opencl.py", line 2493, in futhark_main
    (np.long(group_sizze_2838),))
  File "/home/kodi/.local/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 2168, in enqueue_nd_range_kernel
    global_work_size, local_work_size, c_wait_for, num_wait_for))
  File "/home/kodi/.local/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 632, in _handle_error
    raise e
pyopencl.cffi_cl.RuntimeError: clEnqueueNDRangeKernel failed: OUT_OF_RESOURCES
Makefile:9: recipe for target 'run' failed
```

I can reproduce this with the the N-body example from `futhark-benchmarks`. Curiously, this problem does not trigger on my laptop which also runs on an Intel IGP.

**Comment by Athas** [comment]
Does your Ubuntu machine and laptop have the same hardware and drivers?
Which version of Ubuntu are you using?  I know that the Intel Beignet
drivers used to have a memory leak that manifested itself exactly in
this way, but I don't remember the version.  I know that the version of
Beignet in Debian Testing (1.3) no longer has this leak.  Try 'dpkg -l
beignet' to see which version is installed.

-- 
\  Troels
/\ Henriksen

**Comment by wvdschel** [comment]
I am running Ubuntu 16.04.2, Beignet is version 1.1.1-2, so it might be the affected version.

The laptop is running a different distribution, so it might well have a newer beignet driver.

I'll put this down to the driver being bugged and close this issue.
